feat: add css vars for gradients
holaluz/margarita pull request #354
Opened 2021-02-09 15:50 UTC by sergigraciaj

⚠️ There is an issue with the button-gradient
⚠️ The ma-range gradient is backwards: discuss if there is freedom for the gradient orientation in specifics parts or if the orientation is fixed.

2021-02-09 15:58 UTC, afontcu commented
>  ⚠️ The ma-range gradient is backwards: discuss if there is freedom for the gradient orientation in specifics parts or if the orientation is fixed.

Discussed this with @icurdu a few days ago and Range gradient orientation is fine, but the DS variable should still be left-right. However he can confirm this 😉

2021-02-09 15:59 UTC, afontcu commented on docs/tokens/gradients/gradients.stories.js
> +        <h2 v-text="getName(name)"/>
MaHeading? 😬

2021-02-09 16:07 UTC, afontcu commented on src/components/MaButton/MaButton.css
> +  background-image: var(--gradient-pink-orange-yellow);
Issue here is that Button features a double-sized background, so that it can "slide" when hovering. I'm not quite sure we can handle this otherwise, so I would keep it as an standalone gradient for the button 🤷‍♀️  Let's assume a button is visible enough so that if we change all gradients, we'll notice 😂

2021-02-10 06:52 UTC, edufarre reviewed
Overall, looks good to me. Shall we discuss what should we do with the button before shipping this to prod?

2021-02-15 15:07 UTC, sergigraciaj commented
https://github.com/holaluz/margarita/blob/66936813fb0958c48d0e2144ab6d0f26b8e18777/src/tokens/gradient.js#L4-L5

I decided to name it by its DS name, and to add just the colors and percentage, so the css calling this is responsible of the orientation (as we do in ma-range). This solves the left-to-right gradients and let us do top-to-bottom gradients if needed.

2021-02-15 15:27 UTC, afontcu commented on docs/tokens/gradients/gradients.stories.js
> +        marginTop: '1rem',
Not really important, but: any margin-top declaration smells like a missing Stack 😬

2021-02-15 15:31 UTC, afontcu requested changes
Implementation looks good, but it seems like tokens… have not been generated? There are no tracked changes for `src/css/tokens.css` or its SCSS counterpart.

Didn't the precommit hook trigger the `tokens:build` script?

2021-02-15 16:11 UTC, afontcu commented on docs/tokens/gradients/gradients.stories.js
> +        marginTop: '1rem',
(btw you could've simplify it a bit by simply using Stack as loop parent: `<ma-stack v-for="...">`

2021-02-17 08:03 UTC, edufarre approved these changes
Shall we update the `story` in order to be an written in `mdx` thus just having **1 file** to maintain for its `story` and `docs`>

However, we could tackle this in a future iteration

2021-02-24 17:32 UTC, edufarre approved these changes
Good job mate! 🚀  

Do not forget to update the branch with the latest code additions located in the master branch tho

2021-02-25 07:02 UTC, afontcu approved these changes
LGTM

I'd only fix the indentation on `docs/tokens/colors.stories.mdx` (looks like it's using a 4 spaces indentation)

2021-02-25 11:30 UTC, sergigraciaj commented
> I'd only fix the indentation on `docs/tokens/colors.stories.mdx` (looks like it's using a 4 spaces indentation)

The right one is 2 spaces indentation, yup?
I don't know why I got this issues just in this file... : /

2021-02-25 11:56 UTC, merged