refactor: port ma-stack to ts
holaluz/margarita pull request #531
Opened 2022-05-02 09:41 UTC by alex-castelo

2022-05-02 12:59 UTC, edufarre commented on src/components/MaStack/MaStack.vue
> +    ) as Spacing
this `as Spacing` is really needed? Maybe what we should do instead if give a type to the return value of `getResponsivePropValue`

2022-05-02 12:59 UTC, edufarre commented on src/components/MaStack/MaStack.vue
> +type StackAlignment = keyof typeof alignment
I'd rather have the values here, but it might be just a personal preference.

```suggestion
type StackAlignment = 'fill' | 'right'
```

2022-05-02 12:59 UTC, edufarre commented on src/components/MaStack/MaStack.vue
> +    } as PropOptions<Spacing>,
I believe you missed that this prop can be an array as well
```suggestion
    } as PropOptions<Spacing | Spacing[]>,
```

2022-05-02 12:59 UTC, edufarre commented on src/components/MaStack/MaStack.vue
> +      type: [Array, String] as PropType<StackAlignment>,
```suggestion
      type: [Array, String] as PropType<StackAlignment | StackAlignment[]>,
```

2022-05-02 13:13 UTC, alex-castelo commented on src/components/MaStack/MaStack.vue
> +    } as PropOptions<Spacing>,
You're right! Thanks 👍🏽

2022-05-02 13:26 UTC, alex-castelo commented on src/components/MaStack/MaStack.vue
> +    ) as Spacing
done!

2022-05-02 13:31 UTC, edufarre commented on src/responsive.d.ts
> +  getResponsivePropValue: <T>(values: T | T[]) => T
🚀

2022-05-02 13:33 UTC, edufarre requested changes
I believe you should run the Vetur script again, as some properties still don't have the proper type. Once that is done, looking good to me 💪🏽

2022-05-02 13:48 UTC, edufarre commented on vetur/attributes.json
> +    "type": "array",
🤔 Dunno why looks like we are losing one type (happens the same with other props)

2022-05-02 14:01 UTC, alex-castelo commented on vetur/attributes.json
> +    "type": "array",
I think it's related with type inference, let me take a look

2022-05-03 07:30 UTC, alex-castelo commented on vetur/attributes.json
> +    "type": "array",
The only reason I've found is the optional typing in the component --> `as PropType<Patata | Patata[]>` it seems to break `vetur script` .  I prefer to leave this this way due the final objective is to have TS support instead of Vetur, right?

What do you think about it?

2022-05-03 10:08 UTC, edufarre approved these changes

2022-05-03 10:23 UTC, merged

2022-05-12 11:12 UTC, holaluz-frontend commented
:tada: This PR is included in version 14.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@holaluz/margarita/v/14.0.0-beta.1)
- [GitHub release](https://github.com/holaluz/margarita/releases/tag/v14.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-05-24 07:02 UTC, holaluz-frontend commented
:tada: This PR is included in version 13.8.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@holaluz/margarita/v/13.8.0)
- [GitHub release](https://github.com/holaluz/margarita/releases/tag/v13.8.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: