feat: apply new branding guidelines
holaluz/margarita pull request #551
Opened 2022-05-11 15:01 UTC by Veenders

2022-05-11 15:42 UTC, icurdu requested changes
We also need to change Ma-Link component in order to match ma-button styles

2022-05-11 15:42 UTC, icurdu commented on src/components/MaTextField/MaTextField.css
> +}
The button is displaying weird.
    ```
border-bottom-left-radius: var(--radius-none);
    border-top-left-radius: var(--radius-none);
    padding: 0.5rem;
```

2022-05-11 15:42 UTC, icurdu commented on src/tokens/headings.ts
> +    'letter-spacing': '-2px',
change letter-space to -1.5px on desktop-medium

2022-05-11 15:42 UTC, icurdu commented on src/tokens/headings.ts
> +    'letter-spacing': '-2px',
change letter-space to -1.5px on desktop-medium

2022-05-11 15:42 UTC, icurdu commented on src/tokens/headings.ts
> +    'letter-spacing': '-2px',
change letter-space to -1px on desktop-medium

2022-05-11 15:42 UTC, icurdu commented on src/tokens/headings.ts
> +    'letter-spacing': '-2px',
change letter-space to -0.75px on desktop-medium

2022-05-11 15:42 UTC, icurdu commented on src/components/MaAlert/MaAlert.css
>  }
Can we change the stack gap to 0.75rem inside the alert vue component?

2022-05-12 10:13 UTC, alex-castelo approved these changes

2022-05-26 09:11 UTC, merged

2022-05-26 09:14 UTC, holaluz-frontend commented
:tada: This PR is included in version 14.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@holaluz/margarita/v/14.0.0)
- [GitHub release](https://github.com/holaluz/margarita/releases/tag/v14.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: